apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datavault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/datavault.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: datavault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
