apiVersion: apps/v1
kind: Deployment
metadata:
  name: datavault-processor
  namespace: datavault
spec:
  replicas: 2
  selector:
    matchLabels:
      app: datavault-processor
  template:
    metadata:
      labels:
        app: datavault-processor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: processor
          image: ${DOCKER_USERNAME}/datavault:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: AWS_REGION
              value: us-west-1
            - name: RAW_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: datavault-config
                  key: raw_bucket
            - name: PROCESSED_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: datavault-config
                  key: processed_bucket
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: datavault-processor
  namespace: datavault
spec:
  selector:
    app: datavault-processor
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datavault-config
  namespace: datavault
data:
  raw_bucket: "datavault-raw-data"
  processed_bucket: "datavault-processed-data"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: datavault-processor
  namespace: datavault
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: datavault-processor
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
